---
mainfont: Arial
mainfontoptions: BoldFont=Arial Bold
mainfontoptions: ItalicFont=Arial Italic
mainfontoptions: BoldItalicFont=Arial Bold Italic
fontsize: 11pt
geometry: margin=25mm
documentclass: extarticle
---
